package com.petstore.dao.entities;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AbstractPetPhotosEntity generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractPetPhotosEntity extends com.petstore.dao.AbstractBaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private long petPhotoId;
	private PetEntity petEntity;
	private String photoUrl;

	public AbstractPetPhotosEntity() {
	}

	public AbstractPetPhotosEntity(PetEntity petEntity, String photoUrl) {
		this.petEntity = petEntity;
		this.photoUrl = photoUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pet_photo_id", unique = true, nullable = false)
	public long getPetPhotoId() {
		return this.petPhotoId;
	}

	public void setPetPhotoId(long petPhotoId) {
		this.petPhotoId = petPhotoId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pet_id", nullable = false)
	public PetEntity getPetEntity() {
		return this.petEntity;
	}

	public void setPetEntity(PetEntity petEntity) {
		this.petEntity = petEntity;
	}

	@Column(name = "photo_url", nullable = false, length = 4000)
	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

}
