package com.petstore.dao.entities;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CategoryEntity generated by hbm2java
 */
@Entity
@Table(name = "categories", uniqueConstraints = @UniqueConstraint(columnNames = "category_name"))
public class CategoryEntity extends com.petstore.dao.entities.AbstractCategoryEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public CategoryEntity() {
	}

	public CategoryEntity(String categoryName) {
		super(categoryName);
	}

}
