package com.petstore.dao.entities;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.util.StringUtils;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.petstore.models.Pet;

/**
 * PetEntity generated by hbm2java
 */
@Entity
@Table(name = "pets")
public class PetEntity extends com.petstore.dao.entities.AbstractPetEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static enum PetStatus {
		AVAILABLE, PENDING, SOLD;

		public static PetStatus resolveStatus(String status) {
			PetStatus resolvedStatus = PetStatus.valueOf(status);
			if (resolvedStatus != null)
				return resolvedStatus;
			return PetStatus.AVAILABLE;
		}
	}

	public PetEntity() {
		super();
	}

	public PetEntity(String petName, PetStatus status) {
		super(petName, status.name());
	}

	public PetEntity(CategoryEntity categoryEntity, String petName, PetStatus status, Set<PetPhotosEntity> petPhotosEntities,
			Set<TagEntity> tagEntities) {
		super(categoryEntity, petName, status.name(), petPhotosEntities, tagEntities);
	}

	public PetEntity(Pet newPet) {
	}

	public static int compareByName(PetEntity t1, PetEntity t2) {
		return t1.getPetName().compareTo(t2.getPetName());
	}

	@Transient
	public CategoryEntity getCategory() {
		return super.getCategoryEntity();
	}

	@Transient
	public List<TagEntity> getTags() {
		return super.getTagEntities().parallelStream().sorted(TagEntity::compareByName).collect(Collectors.toList());
	}

	@Transient
	public List<String> getPhotoUrls() {
		return super.getPetPhotosEntities().stream().map(pp -> pp.getPhotoUrl()).filter(s -> !StringUtils.isEmpty(s)).sorted()
				.collect(Collectors.toList());
	}

	@Transient
	@JsonIgnore
	public PetStatus getPetStatus() {
		return PetStatus.resolveStatus(super.getStatus());
	}

	public void setPetStatus(PetStatus petStatus) {
		super.setStatus(petStatus.name());
	}
}
