package com.petstore.dao.entities;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PetPhotosEntity generated by hbm2java
 */
@Entity
@Table(name = "petphotos", uniqueConstraints = @UniqueConstraint(columnNames = { "pet_id", "photo_url" }))
public class PetPhotosEntity extends com.petstore.dao.entities.AbstractPetPhotosEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public PetPhotosEntity() {
	}

	public PetPhotosEntity(PetEntity petEntity, String photoUrl) {
		super(petEntity, photoUrl);
	}
}
